platform :ios, '13.0'

target 'FaceGuard' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'TensorFlowLiteSwift', '~> 2.14'
  pod 'TensorFlowLiteSwift/Metal', '~> 2.14'
  pod 'TensorFlowLiteSwift/CoreML', '~> 2.14'
end
